---
- hosts: ds_64
  user: acsapp
  vars:
  - var1: pjt
  tasks:
  - name: stop the the exiting jar process
    shell: cd /appserver/{{pjt}}/ ; sh run-java-app.sh *.jar stop ; sleep 3



  - name : store jar into tbd
    shell: cd /appserver/{{pjt}}/; ls *capsule.jar
    register: capsule

  - name: stop the the exiting jar process
    shell: cd /appserver/{{pjt}}/ ; sh run-java-app.sh {{capsule.stdout}} stop ; sleep 3

  - name: copy with time stamp
    shell: mv /appserver/{{pjt}}/{{capsule.stdout}} "/backup/{{pjt}}"/{{capsule.stdout}}_`date +%d-%m-%y`

  - name: deploy the new jar file into vertx
    copy: src="{{item}}" dest=/appserver/{{pjt}}/
    with_fileglob:
      - /appserver/jenkins-workspace/{{pjt}}/{{pjt}}/build/libs/*capsule.jar
#      - /home/acsapp/ansi@scripts/jenkins_work_space/{{pjt}}/build/libs/*capsule.jar

  - name: up the application with build
    shell: cd /appserver/acs2-api/ ; nohup sh run-java-app.sh *.jar start &


  - name: checking if its successfully deployed in to  the vertex
    shell: cd /appserver/acs2-api/ ; nohup sh run-java-app.sh *.jar status &
    register: jar_status

  - name: show the output
    debug: var=jar_status.stdout
